// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyGarden.Infrastructure;

namespace MyGarden.Web.Migrations
{
    [DbContext(typeof(GardenDbContext))]
    [Migration("20200712231203_AddSowingTableAndNamesTable")]
    partial class AddSowingTableAndNamesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Garden.Domain.GardenKnowledge.Plants.PlantName", b =>
                {
                    b.Property<Guid>("PlantCharacteristicsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlantCharacteristicsId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlantCharacteristicsId");

                    b.HasIndex("PlantCharacteristicsId1");

                    b.ToTable("PlantNames");
                });

            modelBuilder.Entity("Garden.Domain.GardenKnowledge.Plants.Sowing", b =>
                {
                    b.Property<Guid>("PlantCharacteristicsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.HasKey("PlantCharacteristicsId");

                    b.ToTable("Sowing");
                });

            modelBuilder.Entity("MyGarden.Domain.Garden.GardenModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("UserId")
                        .HasColumnName("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Garden");
                });

            modelBuilder.Entity("MyGarden.Domain.PlantCharacteristics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LatinName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlantCharacteristics");
                });

            modelBuilder.Entity("MyGarden.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyGarden.GardenKnowledge.Domain.GardenAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PlantCharacteristicsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PlantCharacteristicsId");

                    b.ToTable("GardenAction");
                });

            modelBuilder.Entity("Garden.Domain.GardenKnowledge.Plants.PlantName", b =>
                {
                    b.HasOne("MyGarden.Domain.PlantCharacteristics", null)
                        .WithMany("Names")
                        .HasForeignKey("PlantCharacteristicsId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Garden.Domain.GardenKnowledge.Plants.Sowing", b =>
                {
                    b.HasOne("MyGarden.Domain.PlantCharacteristics", null)
                        .WithOne("Sowing")
                        .HasForeignKey("Garden.Domain.GardenKnowledge.Plants.Sowing", "PlantCharacteristicsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MyGarden.Domain.PlantSpacing", "Spacing", b1 =>
                        {
                            b1.Property<Guid>("SowingPlantCharacteristicsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Maximal")
                                .HasColumnType("int");

                            b1.Property<int>("Measure")
                                .HasColumnType("int");

                            b1.Property<int>("Minimal")
                                .HasColumnType("int");

                            b1.HasKey("SowingPlantCharacteristicsId");

                            b1.ToTable("Sowing");

                            b1.WithOwner()
                                .HasForeignKey("SowingPlantCharacteristicsId");
                        });

                    b.OwnsOne("MyGarden.GardenKnowledge.Domain.GardeningDate", "SowingDate", b1 =>
                        {
                            b1.Property<Guid>("SowingPlantCharacteristicsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("MonthsSummary")
                                .HasColumnType("float");

                            b1.HasKey("SowingPlantCharacteristicsId");

                            b1.ToTable("Sowing");

                            b1.WithOwner()
                                .HasForeignKey("SowingPlantCharacteristicsId");
                        });
                });

            modelBuilder.Entity("MyGarden.Domain.Garden.GardenModel", b =>
                {
                    b.OwnsMany("MyGarden.Domain.Garden.Plant", "Plants", b1 =>
                        {
                            b1.Property<Guid>("GardenModelId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<Guid?>("PlantCharacteristicsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("PlantingDate")
                                .HasColumnType("datetime2");

                            b1.HasKey("GardenModelId", "Id");

                            b1.HasIndex("PlantCharacteristicsId");

                            b1.ToTable("Plant");

                            b1.WithOwner()
                                .HasForeignKey("GardenModelId");

                            b1.HasOne("MyGarden.Domain.PlantCharacteristics", "PlantCharacteristics")
                                .WithMany()
                                .HasForeignKey("PlantCharacteristicsId");

                            b1.OwnsMany("MyGarden.Domain.Garden.CompletedAction", "CompletedActions", b2 =>
                                {
                                    b2.Property<Guid>("PlantGardenModelId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("PlantId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<DateTime>("ActionDate")
                                        .HasColumnType("datetime2");

                                    b2.Property<Guid?>("ActionId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("PlantGardenModelId", "PlantId", "Id");

                                    b2.HasIndex("ActionId");

                                    b2.ToTable("CompletedAction");

                                    b2.HasOne("MyGarden.GardenKnowledge.Domain.GardenAction", "Action")
                                        .WithMany()
                                        .HasForeignKey("ActionId");

                                    b2.WithOwner()
                                        .HasForeignKey("PlantGardenModelId", "PlantId");
                                });
                        });
                });

            modelBuilder.Entity("MyGarden.Domain.PlantCharacteristics", b =>
                {
                    b.OwnsOne("MyGarden.GardenKnowledge.Domain.GardeningDate", "FloweringTime", b1 =>
                        {
                            b1.Property<Guid>("PlantCharacteristicsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("MonthsSummary")
                                .HasColumnType("float");

                            b1.HasKey("PlantCharacteristicsId");

                            b1.ToTable("PlantCharacteristics");

                            b1.WithOwner()
                                .HasForeignKey("PlantCharacteristicsId");
                        });
                });

            modelBuilder.Entity("MyGarden.GardenKnowledge.Domain.GardenAction", b =>
                {
                    b.HasOne("MyGarden.Domain.PlantCharacteristics", null)
                        .WithMany("GardenActions")
                        .HasForeignKey("PlantCharacteristicsId");

                    b.OwnsOne("MyGarden.GardenKnowledge.Domain.GardeningDate", "Time", b1 =>
                        {
                            b1.Property<Guid>("GardenActionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("MonthsSummary")
                                .HasColumnType("float");

                            b1.HasKey("GardenActionId");

                            b1.ToTable("GardenAction");

                            b1.WithOwner()
                                .HasForeignKey("GardenActionId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
